# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69b6569f95292a4600bb6faa586b7a8ead38e6f50a14987cd0ed754aff7f3b8c794051042e398bf7c193047aeb59e2dff35c2998064583708c6d3f2697a78bf9

test:
  secret_key_base: d2b1d939a7bc8bb6df3c6ea9f8b8b3ef2216fb185d599e31d95e86aa223b364dfca81d34a62d61da8e305cc291d6ee6cade9566ac4560ad39e06a388e390b855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
